end/demo2/blog/apps/blogapp/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views
from .feed import ArticleFeed
app_name = 'blogapp'

urlpatterns = [
    # url(r'^index/$',views.index,name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^favicon.ico$', views.favicon,name='favicon'),
    url(r'^rss/$', ArticleFeed(),name='rss'),
]

end/demo2/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT

from django.conf.urls import url
from .settings import MEDIA_ROOT
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),
    # path('blogapp/',include('blogapp.urls',namespace='blogapps')),

    # 修改图片路径，允许预览
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    url(r'^search/', include('haystack.urls')),
    path('', include('blogapp.urls', namespace='blogapps')),

]

end/demo2/blog/apps/blogapp/models.py
from django.db import models
# 导入富文本字段（需要先设置根目录）
from DjangoUeditor.models import UEditorField


# Create your models here.

class Ads(models.Model):
    # 使用图片字段 需要安装pillow模块
    img = models.ImageField(upload_to='ads', verbose_name="图片")

    desc = models.CharField(max_length=20, null=True, blank=True, verbose_name="图片描述")

    def __str__(self):
        return self.desc

    class Mate:
        verbose_name = "图片表"


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name="分类名")

    def __str__(self):
        return self.name

    class Mate:
        verbose_name = "分类表"


class Tag(models.Model):
    name = models.CharField(max_length=20, verbose_name="标签名")

    def __str__(self):
        return self.name

    class Mate:
        verbose_name = "标签表"


class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name="文章标题")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="修改时间")
    auther = models.CharField(max_length=20, verbose_name="作者")
    views = models.PositiveIntegerField(default=0, verbose_name="浏览量")
    # body = models.TextField(verbose_name="正文")
    # 使用富文本字段类型
    body = UEditorField(imagePath="imgs/", width="100%", verbose_name="正文")
    tags = models.ManyToManyField(Tag, verbose_name="标签")

    def __str__(self):
        return self.title

    class Mate:
        verbose_name = "文章表"


class Comment(models.Model):
    name = models.CharField(max_length=20, verbose_name="评论人")
    url = models.URLField(default="http://www.zzy.com", verbose_name="个人主页")
    email = models.EmailField(default="1862655@qq.com", verbose_name="个人邮箱")
    body = models.TextField(verbose_name="评论内容")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="所属文章")

    def __str__(self):
        return self.name

    class Mate:
        verbose_name = "评论表"

end/demo2/blog/apps/blogapp/views.py
from django.shortcuts import render, redirect,reverse
from django.http import HttpResponse

from blogapp.forms import CommentForm
from .models import *
# 分页和分页器
from django.core.paginator import Page, Paginator


# Create your views here.

def index(request):
    # return HttpResponse("首页")
    ads = Ads.objects.all()
    type_page = request.GET.get("type")
    year, month, category_id = None, None, None
    if type_page == "date":
        year = request.GET.get("year")
        month = request.GET.get("month")
        articles = Article.objects.filter(create_time__year=year, create_time__month=month).order_by("-create_time")
    elif type_page == "category":
        category_id = request.GET.get("category_id")
        try:
            category = Category.objects.get(id=category_id)
            articles = category.article_set.all()
        except:
            return HttpResponse("标签不合法！")
    elif type_page == "tag":
        tag_id = request.GET.get("tag_id")
        try:
            tag = Tag.objects.get(id=tag_id)
            articles = tag.article_set.all()
        except:
            return HttpResponse("标签不合法！")
    else:
        articles = Article.objects.all()

    # locals()可以返回作用域 局部变量
    # print(locals())
    # return render(request, 'index.html',locals())
    # 添加分页
    paginator = Paginator(articles, 2)
    num = request.GET.get("pagenum", 1)
    page = paginator.get_page(num)
    return render(request, 'index.html', locals())

    # return render(request, 'index.html', {"ads": ads, "page": page,'type':type_page,"year":year,"month":month})



def detail(request, articleid):
    # return HttpResponse("详情")
    if request.method == "GET":
        try:
            article = Article.objects.get(id=articleid)
            article.views += 1
            article.save()
            cf = CommentForm()
            return render(request, 'single.html', locals())
        except:
            return HttpResponse("查无此书")
    else:
        cf = CommentForm(request.POST)
        if cf.is_valid():
            # 此时cf是一个表单，不是实例
            # cf.article = Article.objects.get(id=articleid)
            # 保存前对commit默认值修改为False  comment就是实例了
            comment = cf.save(commit=False)
            comment.article = Article.objects.get(id=articleid)
            comment.save()

            url = reverse("blogapp:detail", args=(articleid,))
            return redirect(to=url)

        else:
            article = Article.objects.get(id=articleid)
            cf = CommentForm()
            errors = "输入格式有误！"
            return render(request, 'single.html', locals())





def contact(request):
    # return HttpResponse("联系我们")
    return render(request, 'contact.html')


def favicon(request):
    return redirect(to="/static/favicon.ico")

end/demo2/blog/templates/base.html
<!DOCTYPE html>
<html>
<body>

</body>
<head>
    {% block Title %}
    <title>博客实战</title>
    {% endblock %}

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>
<body>

<div id="site-header">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>博客实战</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blogapp:index' %}" data-hover="首页">首页</a></li>
                            {# <li class="cl-effect-11"><a href="{% url 'blogapp:detail/3/' %}" data-hover="博客">博客</a></li> #}
                            <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blogapp:contact' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="/search/">
                            <input type="search" placeholder="搜索" required name="q">
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            {% block main %}

            {% endblock %}
            {% block aside %}

            {% endblock %}
        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2020 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">豪哥导航</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">lsh1001</a>修改
                </p>
            </div>
        </div>
    </div>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

end/demo2/blog/templates/base2.html
{% extends 'base.html' %}
{% load myfun %}
{% block Title %}
<title>继承base</title>
{% endblock %}
{% block main %}
{% endblock %}
{% block aside %}
<aside class="col-md-4">
    <div class="widget widget-recent-posts">
        <h3 class="widget-title">最新文章</h3>
        {% get_latest_articles as latest_articles %}

        <ul>
            {% for article in latest_articles %}
            <li>
                <a href="{% url 'blogapp:detail' article.id %}">{{article.title}}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="widget widget-archives">
        <h3 class="widget-title">归档</h3>
        {% get_latest_dates as latest_dates %}
        <ul>
            {% for date in latest_dates %}
            <li>
                <a href="/?type=date&year={{date.year}}&month={{date.month}}">{{date.year}} 年 {{date.month}}月</a>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class="widget widget-category">
        <h3 class="widget-title">分类</h3>
        {% get_categorys as category %}
        <ul>
            {% for c in category %}
            <li>
                <a href="/?type=category&category_id={{c.id}}">{{c.name}}<span class="post-count">({{c.article_set.count}})</span></a>
            </li>
            {% endfor %}

        </ul>
    </div>

    <div class="widget widget-tag-cloud">
        <h3 class="widget-title">标签云</h3>
        {% get_tags as tags %}
        <ul>
            {% for t in tags %}
            <li>
                <a href="/?type=tag&tag_id={{t.id}}">{{t.name}}</a>
            </li>
            {% endfor %}

        </ul>
    </div>
    <div class="rss">
        <a href="{% url 'blogapp:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
    </div>
</aside>
{% endblock %}

end/demo2/blog/templates/index.html
{% extends 'base2.html' %}
{% load myfun %}
{% block Title %}
<title>博客首页</title>
{% endblock %}
{% block main %}
{# {{ads}} #}
<main class="col-md-8">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            {% for a in ads %}
            {% if forloop.counter0 == 0 %}
            <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter0}}" class="active"></li>
            {% else %}
            <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter0}}"></li>
            {% endif %}
            {% endfor%}

        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            {% for a in ads %}
            {% if forloop.counter0 == 0 %}
            <div class="item active">
                <img src="/media/{{a.img}}" alt="...">
                <div class="carousel-caption">
                    <h1>{{a.desc}}</h1>
                </div>
            </div>
            {% else %}
            <div class="item">
                <img src="/media/{{a.img}}" alt="...">
                <div class="carousel-caption">
                    <h1>{{a.desc}}</h1>
                </div>
            </div>
            {% endif %}
            {% endfor%}

        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    {# 遍历所有文章{% for a in articles %} #}
    {% for a in page.object_list %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">

                <a href="{% url 'blogapp:detail' a.id %}">{{a.title}}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{a.category.name}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{a.create_time|date_format}}</time></a></span>
                <span class="post-author"><a href="#">{{a.auther|author_format:"作者"}}</a></span>
                <span class="comments-link"><a href="#">{{a.comment_set.count}} 评论</a></span>
                <span class="views-count"><a href="#">{{a.views}} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
<!--            <p>{{a.body|safe|truncatechars_html:20}}</p>-->
            <p>{{a.body|safe|truncatechars_html:'20'}}</p>
            <div class="read-more cl-effect-14">
                <a href="{% url 'blogapp:detail' a.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% endfor %}

    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination col-md-11">
        <ul>
            {% if page.has_previous %}
            <li class="col-md-2"><a href="/?pagenum={{page.previous_page_number}}&type={{type_page}}&year={{year}}&month={{month}}&tag_id={{tag_id}}&category_id={{category_id}}">上一页</a></li>
            {% endif %}
            {% for pn in page.paginator.page_range %}
            {% if pn == page.number %}
            <li class="current col-md-1"><a href="/?pagenum={{pn}}&type={{type_page}}&year={{year}}&month={{month}}&tag_id={{tag_id}}&category_id={{category_id}}">{{pn}}</a></li>
            {% else %}
            <li class=" col-md-1"><a href="/?pagenum={{pn}}&type={{type_page}}&year={{year}}&month={{month}}&tag_id={{tag_id}}&category_id={{category_id}}">{{pn}}</a></li>
            {% endif %}
            {% endfor %}
            {% if page.has_next %}
            <li class="col-md-2"><a href="/?pagenum={{page.next_page_number}}&type={{type_page}}&year={{year}}&month={{month}}&tag_id={{tag_id}}&category_id={{category_id}}">下一页</a></li>
            {% endif %}
        </ul>
    </div>
</main>
{% endblock %}

end/demo2/blog/templates/search/full-width.html
<!DOCTYPE html>
<html>
<head>
    <title>博客实战</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="css/pace.css">
    <link rel="stylesheet" href="css/custom.css">

    <!-- js -->
    <script src="js/jquery-2.1.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/pace.min.js"></script>
    <script src="js/modernizr.custom.js"></script>
</head>

<body>

<div id="site-header">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>博客实战</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                {% if query %}
                <h3>搜索结果如下：</h3>
                {% for result in page.object_list %}
                <a href="{% url 'blogapp:detail' result.object.id %}"> {{result.object.title}}--{{result.object.id}}</a><br/>
                <article class="post post-2">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="single.html">{{result.object.title}}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{result.object.category.name}}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{result.object.create_time|date_format}}</time></a></span>
                            <span class="post-author"><a
                                    href="#">{{result.object..auther|author_format:"作者"}}</a></span>
                            <span class="comments-link"><a href="#">{{result.object.comment_set.count}} 评论</a></span>
                            <span class="views-count"><a href="#">{{result.object.views}} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{result.object.title}}
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                <p>啥也没找到</p>
                {% endfor %}
                {% endif %}


                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div>
            </main>

        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">zzy0371</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">zzy0371</a>修改
                </p>
            </div>
        </div>
    </div>
</div>

<script src="js/script.js"></script>

</body>
</html>

end/demo2/blog/templates/search/search.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
<!--    {% if query %}-->
<!--    <h3>搜索结果如下：</h3>-->
<!--        {% for result in page.object_list %}-->
<!--        <a href="{% url 'blogapp:detail' result.object.id %}"> {{result.object.title}}&#45;&#45;{{result.object.id}}</a><br/>-->
<!--        {% empty %}-->
<!--        <p>啥也没找到</p>-->
<!--        {% endfor %}-->
<!--    {% endif %}-->
<!--</body>-->
<!--</html>-->
<!DOCTYPE html>
<html>
<head>
    <title>博客实战</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="css/pace.css">
    <link rel="stylesheet" href="css/custom.css">

    <!-- js -->
    <script src="js/jquery-2.1.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/pace.min.js"></script>
    <script src="js/modernizr.custom.js"></script>
</head>

<body>

<div id="site-header">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>博客实战</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                {% if query %}
                <h3>搜索结果如下：</h3>
                {% for result in page.object_list %}
                <a href="{% url 'blogapp:detail' result.object.id %}"> {{result.object.title}}--{{result.object.id}}</a><br/>
                <article class="post post-2">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blogapp:detail' result.object.id %}">{{result.object.title}}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{result.object.category.name}}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{result.object.create_time}}</time></a></span>
                            <span class="post-author"><a
                                    href="#">{{result.object..auther}}</a></span>
                            <span class="comments-link"><a href="#">{{result.object.comment_set.count}} 评论</a></span>
                            <span class="views-count"><a href="#">{{result.object.views}} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{result.object.title}}
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                <p>啥也没找到</p>
                {% endfor %}
                {% endif %}


                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div>
            </main>

        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">zzy0371</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">zzy0371</a>修改
                </p>
            </div>
        </div>
    </div>
</div>

<script src="js/script.js"></script>

</body>
</html>

end/demo2/blog/templates/single.html
{% extends 'base2.html' %}
{% load myfun %}

{% block Title %}
<title>博客文章</title>
{% endblock %}
{% block main %}
<main class="col-md-8">

    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{article.title}}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{article.category}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{article.create_time|date:'Y-m-d H:i:m'}}</time></a></span>
                <span class="post-author"><a href="#">{{article.auther|author_format:"作者"}}</a></span>
                <span class="comments-link"><a href="#">{{article.comment_set.count}} 评论</a></span>
                <span class="views-count"><a href="#">{{article.views}} 阅读</a></span>

            </div>
        </header>
        <div class="entry-content clearfix">
            <p>Django 是使用 Python 编写的一个开源 Web 框架，可以用来快速搭建一个高性能的网站。</p>
            <blockquote><p>Django makes it easier to build better Web apps more quickly and with less
                code.</p>
                <p>Django 让你以更快的速度、更少的代码、更轻松的方式搭建更好的 Web 应用。</p>
            </blockquote>
            {{article.body|safe}}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>

        <form action="#" method="post" class="comment-form">
            {% csrf_token %}

            <div class="row">
                <div class="row">
                    <div class="col-md-4">
                        <label for="{{cf.name.id_for_label}}">{{cf.name.label}}</label>
                        {{cf.name}}
                    </div>
                    <div class="col-md-4">
                        <label for="{{cf.name.id_for_label}}"> {{cf.email.label}}</label>
                        {{cf.email}}
                    </div>
                    <div class="col-md-4">
                        <label for="{{cf.name.id_for_label}}"> {{cf.url.label}}</label>
                        {{cf.url}}
                    </div>
                    <div class="col-md-12">
                        <label for="{{cf.name.id_for_label}}"> {{cf.body.label}}</label>
                        {{cf.body}}
                        {{errors}}
                        <button type="submit" class="comment-btn">发表</button>
                    </div>
                </div>
            </div>    <!-- row -->
        </form>


        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{article.comment_set.count}} </span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in article.comment_set.all %}
                <li class="comment-item">
                    <span class="nickname">{{comment.name}}</span>
                    <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{comment.create_time|date:'Y-d-m H:i:s'}}
                    </time>
                    <div class="text">
                        {{comment.body}}
                    </div>
                </li>
                {% endfor %}


            </ul>
        </div>
    </section>


</main>
{% endblock %}