end/demo3/qiku/apps/qikuapp/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from . import views
from .feed import CurriculumFeed

app_name = 'qikuapp'

urlpatterns = [
    # url(r'^index/$',views.index,name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^loginout/$', views.loginout, name='loginout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^list/$', views.list, name='list'),
    url(r'^buy/(\d+)/$', views.buy, name='buy'),
    url(r'^add/(\d+)/$', views.add, name='add'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^favicon.ico$', views.favicon, name='favicon'),
    url(r'^search/', include('haystack.urls')),
    url(r'^rss/$', CurriculumFeed(), name='rss'),
]

end/demo3/qiku/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

end/demo3/qiku/qiku/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT

from django.conf.urls import url
from .settings import MEDIA_ROOT
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('', include('qikuapp.urls')),

    # 修改图片路径，允许预览
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

end/demo3/qiku/apps/qikuapp/models.py
from django.db import models

# Create your models here.
from DjangoUeditor.models import UEditorField
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    用户类

    """
    telephone = models.CharField(max_length=11, verbose_name="手机号")
    curriculum = models.ManyToManyField("Curriculum")


class Ads(models.Model):
    img = models.ImageField(upload_to="ads", verbose_name="图片")
    desc = models.CharField(max_length=20, null=True, blank=True, verbose_name="图片说明")

    class Mate:
        verbose_name = "图片表"


class Ads2(models.Model):
    img = models.ImageField(upload_to="ads", verbose_name="图片")
    desc = models.CharField(max_length=20, null=True, blank=True, verbose_name="图片说明")

    class Mate:
        verbose_name = "图片表2"


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name="分类名")

    def __str__(self):
        return self.name

    class Mate:
        verbose_name = "分类表"


class Curriculum(models.Model):
    name = models.CharField(max_length=20, verbose_name="课程名")
    introduce = models.CharField(max_length=120, verbose_name="课程介绍")
    img = models.ImageField(upload_to="imgs", verbose_name="课程图片")
    category = models.ManyToManyField(Category, verbose_name="授课分类")
    price = models.PositiveIntegerField(default=1000, verbose_name="课程费用")
    days = models.PositiveIntegerField(default=7, verbose_name="课程时长")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="开课时间")
    teacher = models.ForeignKey('Teacher', on_delete=models.CASCADE, verbose_name="授课教师")

    def __str__(self):
        return self.name

    class Mate:
        verbose_name = "课程表"


class Teacher(models.Model):
    name = models.CharField(max_length=20, verbose_name="教师名")

    field = models.CharField(max_length=50, verbose_name="权威领域")
    # body = models.TextField(verbose_name="正文")
    # 使用富文本字段类型
    introduce = UEditorField(imagePath="imgs/", width="100%", verbose_name="简介")
    stars = models.PositiveIntegerField(default=3, verbose_name="评价星级")

    def __str__(self):
        return self.name

    class Mate:
        verbose_name = "教师表"


class Comment(models.Model):
    name = models.CharField(max_length=20, verbose_name="评论人")
    url = models.URLField(default="http://www.zzy.com", verbose_name="个人主页")
    email = models.EmailField(default="1862655@qq.com", verbose_name="个人邮箱")
    body = models.TextField(verbose_name="评论内容")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
    curriculum = models.ForeignKey(Curriculum, on_delete=models.CASCADE, verbose_name="所属课程")

    def __str__(self):
        return self.name

    class Mate:
        verbose_name = "评论表"

end/demo3/qiku/templates/培训信息.html
{% extends 'base.html' %}
{% load myfun %}
{% block Title %}
<title>课程列表</title>
{% endblock %}
{% block body %}
<script type="/static/text/javascript">
var obj11 = document.getElementById("inner");
var top11 = getTop(obj11);
var isIE6 = /msie 6/i.test(navigator.userAgent);
window.onscroll = function(){

	var bodyScrollTop = document.documentElement.scrollTop || document.body.scrollTop;
	if (bodyScrollTop > top11){
		obj11.style.position = (isIE6) ? "absolute" : "fixed";
		obj11.style.top = (isIE6) ? bodyScrollTop + "px" : "0px";
	} else {
		obj11.style.position = "static";
	}
}
function getTop(e){

	var offset = e.offsetTop;
	if(e.offsetParent != null) offset += getTop(e.offsetParent);
	return offset;
}











</script>
<!--js-->
<div class="index_show">

    <ul class="bxslider" id="index-bxslider">
        {% for ads in ads2 %}
        <li class="item{{forloop.counter}}" style="background: url(/media/{{ads.img}}) center 0 no-repeat;"></li>
        {% endfor %}


    </ul>

    <div id="bx-pager">
        {% for ads in ads2 %}
        <a data-slide-index="{{forloop.counter0}}" href="javascript:void(0);">{{forloop.counter}}</a>
        {% endfor %}
    </div>

</div>

<script type="/static/text/javascript" src="/static/js/jQuery.v1.8.3-min.js"></script>
<script type="/static/text/javascript" src="/static/js/jquery.bxslider.min.js"></script>
<script type="/static/text/javascript" src="/static/js/zzsc.js"></script>
<!--路径-->
<div class="wrapp pt10 overflow clearfix f18 l-35">
    <p class="fl"><img src="/static/images/t.jpg" class="fl pt15 pr10"/> <a href="#">首页</a> > <em class="red">培训信息</em>
    </p>
</div>
<!--分类-->

<div class=" px_li  mt15 overflow clearfix  mb10 ">
    <dl>

        <dt>课程分类</dt>
        <dd>
            {% for category in categories %}
            <a href="/list?type=category&category_id={{category.id}}">{{category.name}}</a>

            {% endfor %}
        </dd>
    </dl>
    <dl>
        <dt>价格分类</dt>
        <dd>
            {% get_latest_curriculum_price as curriculum%}
            {% for curriculum in curriculum %}
            <a href="/list?type=price&curriculum_price={{curriculum.price}}">{{curriculum.price}}</a>

            {% endfor %}
        </dd>
    </dl>
    <dl>
        <dt>教师课程</dt>
        <dd>
            {% for teacher in teachers %}
            <a href="/list?type=teacher&teacher_id={{teacher.id}}">{{teacher.name}}</a>

            {% endfor %}
        </dd>
    </dl>

</div>


<div class="youthModel wrapp clearfix overflow">

    <ul class="modelList">
        {# 遍历所有课程{% for c in curriculum %} #}

        {% for c in page.object_list %}
        <li class="clearfix">
            <a target="_blank" class="modelImg" href="{% url 'qikuapp:detail' c.id %}"><img src="/static/images/martians_club.jpg"></a>
            <div class="modelRight tl">
                <a target="_blank" class="modelTitle" href="{% url 'qikuapp:detail' c.id %}">{{c.name}}</a>
                <div class="modelIntro tl">
                    {{c.introduce}}
                </div>
                <div class="w100 clearfix">
                    <ol class="fr pt5">已报名:<em class="red">{{c.user_set.all.count}}</em></ol>
                </div>
                <div class="w100 pt5 overflow clearfix tl">
                    授课时长：{{c.days}} (天)&nbsp; &nbsp; &nbsp; &nbsp; 讲师：{{c.teacher}}
                </div>
            </div>
        </li>

        {% endfor %}

    </ul>
</div>

<div class="page pt30 overflow clearfix pb25 ">
    <ul>
        <li class="fl">
            {% if page.has_previous %}
            <a href="/list?pagenum={{page.previous_page_number}}&type={{type_page}}&category_id={{category_id}}&teacher_id={{teacher_id}}">上一页</a>
            {% endif %}
            {% for pn in page.paginator.page_range %}
            {% if pn == page.number %}
            <a class="cur" href="/list?pagenum={{pn}}&type={{type_page}}&category_id={{category_id}}&teacher_id={{teacher_id}}">{{pn}}</a>
            {% else %}
            <a href="/list?pagenum={{pn}}&type={{type_page}}&category_id={{category_id}}&teacher_id={{teacher_id}}">{{pn}}</a>
            {% endif %}
            {% endfor %}
            {% if page.has_next %}

            <a href="/list?pagenum={{page.next_page_number}}&type={{type_page}}&category_id={{category_id}}&teacher_id={{teacher_id}}">下一页</a>
            {% endif %}

        </li>


        <li class="fr">
            <em class="fl">共{{page.paginator.num_pages}}页 到&nbsp;
                <input name="pagename" type="text" size="3" class="boderr" style="height:30px"/>&nbsp;页
            </em>
            <a href="/list?pagenum={{pagename}}&type={{type_page}}" class="cur fr">确定</a>
        </li>
    </ul>
</div>

{% endblock %}

end/demo3/qiku/templates/提交订单.html
{% extends 'base.html' %}
{% load myfun %}
{% block Title %}
<title>购物车</title>

{% endblock %}
{% block body %}
{# 身体 #}


<script type="/static/text/javascript">
var obj11 = document.getElementById("inner");
var top11 = getTop(obj11);
var isIE6 = /msie 6/i.test(navigator.userAgent);
window.onscroll = function(){
 
	var bodyScrollTop = document.documentElement.scrollTop || document.body.scrollTop;
	if (bodyScrollTop > top11){
		obj11.style.position = (isIE6) ? "absolute" : "fixed";
		obj11.style.top = (isIE6) ? bodyScrollTop + "px" : "0px";
	} else {
		obj11.style.position = "static";
	}
}
function getTop(e){
 
	var offset = e.offsetTop;
	if(e.offsetParent != null) offset += getTop(e.offsetParent);
	return offset;
}



</script>
<!--js-->
<!--提交订单-->
<div class="wrapp pt50 overflow clearfix tl f18">
    确认订单信息
</div>
<div class="wrapp pt35 sp_list  overflow">
    <ul>
        <li class="sp_list_r1 tc f16">课程名称</li>
        <li class="sp_list_r2 tc f16">代课教师</li>
        <li class="sp_list_r3 tc f16">单价/时长(元)</li>
    </ul>
</div>
{% for c in request.user.curriculum.all %}

<div class="wrapp pt35 sp_list  overflow">
    <ul>

        <li class="sp_list_r1 tl f12 hui  ">
            <a href="#"><img src="/static/images/goumai_r1_c1.jpg" width="120" height="90" class="fl mr25"/></a>
            <a href="#" class="red f14">{{c.name}}</a><br/>
            {{c.introduce}}
        </li>
        <li class="sp_list_r2  ">{{c.teacher}}</li>
        <li class="sp_list_r3 cs f18 fon_z  ">￥{{c.price}}/{{c.days}}天</li>

    </ul>
</div>
{% endfor %}

<div class="wrapp overflow bg_g clearfix mt30">
    <ul>
        <li>运送方式: 普通配送快递￥10.00</li>
        <li>发货时间:卖家承诺订单在买家付款后, 30天内发货</li>
        <li>
            <script language="javascript" type="/static/text/javascript">

function goods_cut(){

var num_val=document.getElementById('number');

var new_num=num_val.value;

var Num = parseInt(new_num);

if(Num>1)Num=Num-1;

num_val.value=Num;

}

function goods_add(){

var num_val=document.getElementById('number');

var new_num=num_val.value;

var Num = parseInt(new_num);

Num=Num+1;

num_val.value=Num;

}



            </script>
            <p class="fl mr10">使用积分:</p>
            <div class="tc-amount fl pt10">
                <span class="goods_cut fl" onclick="goods_cut();changePrice();"><img src="/static/images/plus1.gif"
                                                                                     alt="减少" width="15"
                                                                                     height="15"/></span>
                <input name="number" type="text" id="number" value="1" size="4" onblur="changePrice()"
                       style="border:1px solid #ccc; " class="fl mt5"/>
                <span class="goods_add fl" onclick="goods_add();changePrice();"><img src="/static/images/plus2.gif"
                                                                                     alt="增加" width="15"
                                                                                     height="15"/></span>
            </div>
            <p class="fl hui f12 ml10">(目前你有<em class="f18 red">200</em>积分)</p>
        </li>
    </ul>
</div>

<div class="wrapp clearfix pt50 overflow tr l-35">
    <ul>
        <li class="tr">实付款：<em class="f24 red ">￥{{ money}}</em></li>
        <li class="tr">可获积分<em class="f18 red ">{{money_to_integral}}</em></li>
        <li>
            <input type="button" value="提交订单" class="tjdd fr"/>
        </li>
    </ul>
</div>
{% endblock %}

end/demo3/qiku/templates/登录.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>登录</title>
    <link href="/static/css/login.css" rel="stylesheet">
</head>

<body>
<div class="login-headbox" data-gct="1">
    <div class="login-head clearfix" data-gct="1">
        <div class="login-logo-box fl clearfix">
            <a target="_blank" href="http://www.#.com" class="login-logo fl"><img src="/static/images/logr2_c2.jpg"
                                                                                  style="padding-top:3px; padding-left:10px"/></a>
            <h1 class="fl">会员登录</h1>
        </div>
        <a target="_blank" class="help-center fr" href="http://help.gongchang.com">帮助中心</a>
    </div>
</div>

<div class="login-box login" data-gct="2" style="margin-top:140px">
    <div class="lb-title" data-gct="1">
        <h1>你必须要登陆才能进行下一步操作</h1>
        <a href="https://work.gongchang.com" target="_blank" class="lbt-reg">供应商登录</a>
    </div>
    <form method="post" action="#" id="login_form" class="nice-validator n-default" novalidate="novalidate">
        {% csrf_token %}

        <div class="lb-content">
            <div class="lbc-box">
                <div class="lbc-row">
                    <label class="lbc-name">采购会员帐号：</label>
                    <input type="text" name="username" placeholder="手机/邮箱/用户名" class="lbc-ipt n-invalid"
                           aria-required="true" aria-invalid="true" data-inputstatus="error"><span
                        class="msg-box n-right" style="" for="username"><span role="alert"
                                                                              class="msg-wrap n-error"><span
                        class="n-icon"></span></span></span>
                </div>
                <div class="lbc-row login-password">
                    <label class="lbc-name">密码：</label>
                    <input type="password" name="password" placeholder="请输入您的密码" class="lbc-ipt" aria-required="true">
                    <a href="/forget.html" class="login-pwd-forget">忘记密码？</a>
                </div>
            </div>
            <div class="lbc-obox">
                <div class="lbc-row lbc-fj clearfix">
                    <label class="fl"><input type="checkbox" value="1" name="remember"> 7天内记住我</label>
                    <span class="fr">没有帐号？<a href="{% url 'qikuapp:register' %}">立即注册</a></span>
                </div>
                <div class="lbc-row btn-box">
                    <input type="hidden" value="https://i.gongchang.com//static.gcimg.net/i/201508/3VbnieYLc4.png8.png"
                           name="url">
                    <button type="submit" class="lbc-loginnow">立即登录</button>
<!--                    <em>{{error}}</em>-->

<!--                    <em>{{request.user}}</em>-->
<!--                    <em>{{user}}</em>-->
<!--                    {{user.username}}-->
                    <!--                    <button type="submit" class="lbc-loginnow"><a href="{% url 'qikuapp:list' %}">模拟登录</a></button>-->
                </div>
            </div>
        </div>
    </form>
</div>


<div class="login-footer" data-gct="3" style="margin-top:180px">
    <div class="gci-href" data-gct="1">
        <a target="_blank" href="http://www.gongchang.com/about/">网站首页</a>|<a target="_blank"
                                                                              href="http://seller.gongchang.com/dianjintai/">客服中心</a>|<a
            target="_blank" href="http://help.gongchang.com/service/">问题反馈</a>
    </div>
    <div class="gci-copyright" data-gct="2">Copyright &copy; 2008-2016 GongcChang.com All Rights Reserved 训训网权所有
        豫ICP备11020782号-14 <span id="gc_com_runtime">6.17ms</span></div>
</div>

</body>
</html>

end/demo3/qiku/templates/购买页面.html
{% extends 'base.html' %}
{% load myfun %}
{% block Title %}
<title>课程详情</title>

{% endblock %}
{% block body %}
{# 身体 #}


<script type="/static/text/javascript">
var obj11 = document.getElementById("inner");
var top11 = getTop(obj11);
var isIE6 = /msie 6/i.test(navigator.userAgent);
window.onscroll = function(){

	var bodyScrollTop = document.documentElement.scrollTop || document.body.scrollTop;
	if (bodyScrollTop > top11){
		obj11.style.position = (isIE6) ? "absolute" : "fixed";
		obj11.style.top = (isIE6) ? bodyScrollTop + "px" : "0px";
	} else {
		obj11.style.position = "static";
	}
}
function getTop(e){

	var offset = e.offsetTop;
	if(e.offsetParent != null) offset += getTop(e.offsetParent);
	return offset;
}







</script>
<!--js-->
<div class="index_show">

    <ul class="bxslider" id="index-bxslider">
        {% for ads in ads2 %}
        <li class="item{{forloop.counter}}" style="background: url(/media/{{ads.img}}) center 0 no-repeat;"></li>
        {% endfor %}


    </ul>

    <div id="bx-pager">
        {% for ads in ads2 %}
        <a data-slide-index="{{forloop.counter0}}" href="javascript:void(0);">{{forloop.counter}}</a>
        {% endfor %}
    </div>

</div>

<script type="/static/text/javascript" src="/static/js/jQuery.v1.8.3-min.js"></script>
<script type="/static/text/javascript" src="/static/js/jquery.bxslider.min.js"></script>
<script type="/static/text/javascript" src="/static/js/zzsc.js"></script>
<!--路径-->
<div class="wrapp pt10 overflow clearfix f18 l-35">
    <p class="fl"><img src="/static/images/t.jpg" class="fl pt15 pr10"/> <a href="/list">首页</a> > <a
            href="/list?type=teacher&teacher_id={{curriculum.teacher.id}}">{{curriculum.teacher}}</a> >
        <em class="red">{{curriculum.name}}</em></p>
</div>

<!--购买-->
<div class="wrapp pt20 overflow clearfix ">
    <img src="/static/images/goumai_r1_c1.jpg" width="400" height="300" class="fl"/>
    <div class="w782 fr overflow tl l-24">
        <h5 class="tl l-35 f20">{{curriculum.name}}</h5>
        <ol class="f12 hui tl">共{{curriculum.days}}天课程 &nbsp; &nbsp;|&nbsp;&nbsp; <img
                src="/static/images/goumai_r3_c7.jpg"/> ({{curriculum.teacher.stars}}) &nbsp;&nbsp;|&nbsp; &nbsp;239490人学习
        </ol>
        <ul>
            <li class="pt5">价格:<em class="red f18">￥{{curriculum.price}}</em></li>
            <li class="pt5">课程说明:{{curriculum.introduce}}</li>
            <li class="pt5">服费特权:<span class="tl"><img src="/static/images/goumai_r5_c8.jpg "/> 24小时内讲师答疑</span> <span
                    class="tl"><img src="/static/images/goumai_r5_c13.jpg "/>所有课时永久免费 <img
                    src="/static/images/goumai_r5_c15.jpg "/> 专属资料下载 <img src="/static/images/goumai_r5_c19.jpg "/> 购买课程返学分</span>
            </li>
        </ul>
        <dl>
            <dd><a href="{% url 'qikuapp:buy' curriculum.id %}" class="bg2">购买课程</a></dd>
            <dd><a href="{% url 'qikuapp:add' curriculum.id %}" class="bg2">加入购物车</a></dd>
        </dl>
        <div class="w100 pt15 clearfix fenx ">
            <ul>
                <li><img src="/static/images/goumai_r7_c5.jpg"/> <a href="#">收藏</a></li>
                <li>
                    <div class="bdsharebuttonbox fl" style="width:20px; height:30px; overflow:hidden">
                        <a href="#" class="bds_more" data-cmd="more"></a>
                        <a href="#" class="bds_qzone" data-cmd="qzone"></a>
                        <a href="#" class="bds_tsina" data-cmd="tsina"></a>
                        <a href="#" class="bds_tqq" data-cmd="tqq"></a>
                        <a href="#" class="bds_renren" data-cmd="renren"></a>
                        <a href="#" class="bds_weixin"  data-cmd="weixin"></a>
                    </div>
                    <script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdPic":"","bdStyle":"0","bdSize":"16"},"share":{},"image":{"viewList":["qzone","tsina","tqq","renren","weixin"],"viewText":"分享到：","viewSize":"16"},"selectShare":{"bdContainerClass":null,"bdSelectMiniList":["qzone","tsina","tqq","renren","weixin"]}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];







                    </script>
                    <div class="fl "> 分享</div>
                </li>
                <li><img src="/static/images/goumai_r7_c10.jpg" class="pr5"/><a href="#" class="red">推广挣现金</a></li>
            </ul>
        </div>
    </div>
</div>


<div class="wrapp pt50 overflow clearfix tl f18">
    评价商品
</div>

<div class="pingjia  overflow mt40 ">
    <div class="w100 l-35">
        <p class="f18 tl fl ">其它买家需要你的建议啊</p>
        <span class="fr tl"><img src="/static/images/p.jpg"/> 认真填写还可以获得<em class="cs f16">10</em>积分啊</span>
    </div>
    <div class="w100 clearfix pt20 overflow">
        <form action="#" method="post">
            {% csrf_token %}
            <ul>
                <li class="tl l-30">{{cf.name.label}}</li>
                <li class="tl pt20">
                    {{cf.name}}
                </li>
                <li class="tl l-30">{{cf.email.label}}</li>
                <li class="tl pt20">
                    {{cf.email}}
                </li>
                <li class="tl l-30">{{cf.url.label}}</li>
                <li class="tl pt20">
                    {{cf.url}}
                </li>
                <li class="tl l-30">{{cf.body.label}}</li>
                <li class="tl pt20">
                    {{cf.body}}
                </li>

                <li class="tl">
                    <input type="submit" value="提交评价" class="tjdd fl"/>
                </li>
            </ul>
        </form>
    </div>
</div>


<!--区域-->
<div class="wrapp pt20 overflow clearfix pb50 ">
    <!--left-->
    <div class="w880 fl overflow">
        <!--切换-->

        <script>
<!--
/*第一种形式 第二种形式 更换显示样式*/
function setTab(name,cursel,n){
for(i=1;i<=n;i++){
var menu=document.getElementById(name+i);
var con=document.getElementById("con_"+name+"_"+i);
menu.className=i==cursel?"hover":"";
con.style.display=i==cursel?"block":"none";
}
}
//-->







        </script>
        <div id="Tab622">
            <div class="Menubox622">
                <ul>
                    <li id="one1" onmousedown="setTab('one',1,2)" class="hover">培训内容
                    </li>
                    <li id="one2" onmousedown="setTab('one',2,2)" class="">累计评价</li>
                </ul>

            </div>
            <div class="Contentbox622">
                <div id="con_one_1" class="hover" style="display: block;">
                    <div class="about_inf1">
                        <ul>
                            <li>商品名称:乐悠居沙发</li>
                            <li>商品编号:3490</li>

                        </ul>

                    </div>
                    <div class="about_inf2">
                        <!--                        <p><img src="/static/images/shangpin_r22_c17.jpg"/></p>-->
                        <!--                        <p><img src="/static/images/shangpin_r27.jpg"/></p>-->
                    </div>


                </div>
                <div id="con_one_2" style="display: none;">

                    <div class="pinglun_bot pb20">
                        <ul>
                            {% for comment in curriculum.comment_set.all %}

                            <li>
                                <h3 class="f14 huise tr l-26 ">{{comment.create_time|date:'Y-m-d H:i:s'}}</h3>
                                {{comment.name}}
                                <span class="bg12_t"><img src="/static/images/p_r2_c2.jpg"/></span>
                                <ol>
                                    {{comment.body}}
                                </ol>
                            </li>
                            {% endfor %}


                        </ul>
                    </div>


                </div>
            </div>
        </div>
        <!--切换-->
    </div>


    <div class="w298 fr overflow">
        <div class="w100 f20 tl l-30">
            <img src="/static/images/goumai_r10_c20.jpg" class="fl mr10 pt10"/> 扫一扫 手机也能看
        </div>
        <div class="w100 pt15 clearfix overflow">
            <img src="/static/images/goumai_r3_c6.jpg"/>
        </div>
        <div class="w100 f20 tl l-30 pt20">
            <img src="/static/images/goumai_r10_c20.jpg" class="fl mr10 pt10"/> 对此感兴趣的人
        </div>
        <div class="tu clearfix overflow w100">
            <ul>
                <li><a href="#"><img src="/static/images/goumai_r6_c7.jpg" width="42" height="42"/></a></li>
                <li><a href="#"><img src="/static/images/goumai_r6_c7.jpg" width="42" height="42"/></a></li>
                <li><a href="#"><img src="/static/images/goumai_r6_c7.jpg" width="42" height="42"/></a></li>
                <li><a href="#"><img src="/static/images/goumai_r6_c7.jpg" width="42" height="42"/></a></li>
            </ul>
        </div>


    </div>
    <div class="w58" style=" margin-top:100px"></div>

    <div class="box_bg clearfix overflow f20 w100">
        <div class="wrapp overflow">
            <ul>
                <li><a href="#">我要分析</a></li>
                <li><a href="#">我要报名</a></li>
            </ul>
        </div>
    </div>


    {% endblock %}