end/demo1/bookdemo/bookdemo/urls.py
from django.contrib import admin
from django.urls import path,include

# 路由（网址） 每一个网站均需要绑定视图函数 视图函数给予页面返回
# MVT   V视图函数 3个作用 1.接受数据2.数据处理3.返回响应
from django.http import HttpResponse


# def index(request):
#     return HttpResponse("这里是首页")
#
#
# def list(request):
#     return HttpResponse("这里是列表页")
#
#
# def json_data(request):
#     return HttpResponse("{'name':'zzy','age':'20'}")


urlpatterns = [
    path('admin/', admin.site.urls),
    # # 将admin路由和index视图函数绑定
    # path('index/', index,),
    # # 将list路由和list视图函数绑定
    # path('list/', list,),
    # path('json/', json_data,),
    # 多个应用 为了方便管理 1.使用path将booktest的路由 进行包含
    # path('booktest/',include('booktest.urls',)),
    # 优化 因为只有一个应用 可以省略booktest/
    path('',include('booktest.urls',namespace='booktest')),
    path('polls/',include('polls.urls',namespace='polls')),
    path('vote/',include('vote.urls',namespace='vote')),
    path('download/',include('download.urls',namespace='download')),

]

# 项目的所有路由地址配置文件
# admin路由是django自带的后台管理路由

# 总的路由匹配文件 == 项目路由文件  使用include包含应用路由文件

end/demo1/bookdemo/booktest/urls.py
# 引入路由绑定函数
from django.conf.urls import url

from . import views
# 应用名
app_name = "booktest"
#
# 2.每一个路由文件中 必须编写路由数组
urlpatterns = [
    # url(r'^index/$', views.index),
    # 首页优化 http://127.0.0.1:8000/ 直接进入首页
    url(r'^$', views.index,name='index'),
    # 第一个参数就是路由 第二个是视图函数
    url(r'^list/$',views.list,name='list'),
    url(r'^about/$',views.about,name='about'),
    # 以^开始，以$结束 更加严谨
    # 使用正则分组 (\d+) 将正则分组匹配到的内容作为实参传递给视图函数
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    # url(r'^detail/(?P<abc>\d+)/$', views.detail),

    # 删除功能
    url(r'^delbook/(\d+)/$', views.delbook, name='delbook'),
    url(r'^delhero/(\d+)/$', views.delhero, name='delhero'),
    # 添加英雄
    url(r'^addhero/(\d+)/$', views.addhero, name='addhero'),
    url(r'^addbook/$', views.addbook, name='addbook'),
    # 编辑英雄
    url(r'^edithero/(\d+)/$', views.edithero, name='edithero'),
    url(r'^editbook/(\d+)/$', views.editbook, name='editbook'),

]

end/demo1/bookdemo/vote/urls.py
from django.conf.urls import url

from . import views

app_name = "vote"
urlpatterns = [
    # 一、视图函数FBV
    url(r'^$', views.index, name='index'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^result/(\d+)/$', views.result, name='result'),
    # 二、视图类CBV
    # url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^detail/(\d+)/$', views.DetailView.as_view(), name='detail'),
    #
    # url(r'^result/(\d+)/$', views.Result.as_view(), name='result'),

    url(r'^look/$', views.IndexView.as_view(), name='look'),

    url(r'^login/$', views.login, name='login'),
    url(r'^regist/$', views.regist, name='regist'),
    url(r'^loginout/$', views.loginout, name='loginout'),
]

end/demo1/bookdemo/templates/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
</head>
<body>
<form action="#" method="post">
    {% csrf_token %}
    书籍名称：<input type="text" name="title" placeholder="请输入书籍名称">
    <br>
    书籍价格：<input type="text" name="price" placeholder="请输入书籍价格">
    <br>

    出版日期：<input type="text" name="pub_date" placeholder="请输入出版日期">
    <br>

    <input type="submit" value="提交">

</form>

</body>
</html>

end/demo1/bookdemo/templates/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加英雄</title>
</head>
<body>
<div class="container">
    {# 发起post请求#}
    <form action="#" method="post">
        {% csrf_token %}
        <p>人物<input type="text" name="heroname" placeholder="输入角色"></p>
        <p>性别<input type="radio" name="sex" value="female" checked>女<input type="radio" name="sex" value="male" checked>男
        </p>
        <p>描述<input type="text" name="content" placeholder="输入角色描述"></p>
        <input type="submit" value="提交">
    </form>
</div>
</body>
</html>

end/demo1/bookdemo/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>
<div class="container">
    <h1>这里是详情页</h1>
    <div>
        <h2>书名：{{book.title}}</h2>
        <h2>价格：{{book.price}}元/本</h2>
        <h2>出版日期：{{book.pub_date}}</h2>
        <h3>书中人物</h3>
        {% for hero in book.hero_set.all%}
        <h3>
            <li>{{hero.name}}--{{hero.gender}}
                <button><a href="{%url 'booktest:delhero' hero.id %}">删除英雄</a></button>
                <button><a href="{%url 'booktest:edithero' hero.id %}">编辑英雄</a></button>
            </li>
        </h3>
        {% endfor %}



        <button><a href="{%url 'booktest:addhero' book.id %}">添加英雄</a></button>
    </div>
    <div class="end">
        <!--         以下是优化   <button><a href="/booktest/index/">返回列表页</a></button>-->
        <!--            <button><a href="/">返回列表页</a></button>-->
        <button><a href="{%url 'booktest:index' %}">返回列表页</a></button>

    </div>
</div>

</body>
</html>

end/demo1/bookdemo/templates/editbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改书籍</title>
</head>
<body>
<form action="#" method="post">
    {% csrf_token %}

    书籍名称：<input type="text" name="title" value={{book.title}}>
    <br>
    书籍价格：<input type="text" name="price" value={{book.price}}>
    <br>

    出版日期：<input type="date" name="pub_date" value={{book.pub_date}}>
    <br>

    <input type="submit" value="提交">

</form>
</body>
</html>

end/demo1/bookdemo/templates/edithero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑英雄</title>
</head>
<body>
<div class="container">

    <form action="#" method="post">
        {% csrf_token %}
        人物姓名：<input type="text" name="heroname" value={{hero.name}}>
        <br>
        人物描述：<input type="text" name="content" value={{hero.content}}>
        <br>

        {% if hero.gender == "male" %}
        人物性别：<input type="radio" name="sex" value="female">女<input type="radio" name="sex" value="male" checked>男
        {% else %}
        人物性别：<input type="radio" name="sex" value="female" checked>女<input type="radio" name="sex" value="male">男
        {% endif%}
        <br>

        <input type="submit" value="提交">

    </form>
</div>
</body>
</html>

end/demo1/bookdemo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
<div class="container">
    <h1>这是项目首页</h1>
    <div>
        <div class="center">
            <img src="/static/img/2.png" alt="">
        </div>
        <h2>所有的书籍共({{books.count}})本</h2>
        {% for b in books%}
        <!--        <a href="/booktest/detail/{{b.id}}/">下面是优化-->
        <!--        <a href="/detail/{{b.id}}/">-->
        {# 高级注释 提高性能#}

        <li>
            <a href="{% url 'booktest:detail' b.id %}"> {{b.id}}--{{b.title }}--{{b.price }}--{{b.pub_date }}</a>
            <button><a href="{% url 'booktest:delbook' b.id%}">删除</a></button>
            <button><a href="{% url 'booktest:editbook' b.id%}">修改</a></button>
        </li>

        {% endfor%}

        <h2>
            <button><a href="{% url 'booktest:addbook'%}">添加书籍</a></button>
            <button><a href="{% url 'polls:index'%}">进入投票1</a></button>
            <button><a href="{% url 'vote:index'%}">进入投票2</a></button>
            <button><a href="http://127.0.0.1:8000/download/require.txt">下载1</a></button>
            <button><a href="http://127.0.0.1:8000/download/templates/1.txt">下载2</a></button>
            <button><a href="http://127.0.0.1:8000/download/./require.txt">下载3</a></button>
        </h2>

    </div>
</div>

</body>
</html>

end/demo1/bookdemo/templates/polls_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票详情</title>
    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>
<div class="container">
    <h1>这里是投票详情页</h1>

    <h3>问题：{{problem}}</h3>
    <form action="#" method="post">
        {% csrf_token %}
        <p>投票选项</p>

        <br>
        {% for option in problem.problems.all %}

        <input type="radio" name="p" value="1" checked>{{option.option1}}
        <input type="radio" name="p" value="2">{{option.option2}}
        {# 研究半天不知道代码怎么错，原来是格式不规范#}
        {% if problem.option3_votes %}
        <input type="radio" name="p" value="3">{{option.option3}}
        {% endif%}


        {% if problem.option4_votes %}
        <input type="radio" name="p" value="4">{{option.option4}}

        {% endif%}


        {% endfor %}


        <input type="submit" value="投票">
    </form>

    <button><a href="{% url 'polls:index' %}">返回</a></button>
</div>
</body>
</html>

end/demo1/bookdemo/templates/polls_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票首页</title>
    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>
<div class="container">
    <h1>这是投票首页</h1>
    <h2>投票信息汇总</h2>
    {% for problem in problems%}
    <p>投票{{problem.id}}：<a href="{% url 'polls:detail' problem.id %}">{{problem}}</a></p>
    {% endfor %}
    <br>
    <button><a href="{% url 'booktest:index'%}">主菜单</a></button>
</div>

</body>
</html>

end/demo1/bookdemo/templates/polls_votenums.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>票数详情</title>
    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>
<div class="container">
    <h1>当前票数</h1>
    {{problem}}
    {% for option in problem.problems.all %}
    <br>

    {{option.option1}}--{{problem.option1_votes}}
    <br>
    {{option.option2}}--{{problem.option2_votes}}
    <br>
    {% if problem.option3_votes %}
    {{option.option3}}--{{problem.option3_votes}}
    {% endif %}
    <br>
    {% if problem.option4_votes %}
    {{option.option4}}--{{problem.option4_votes}}
    {% endif %}

    {% endfor %}
    <br>
    <button><a href="{%url 'polls:index' %}">返回首页</a></button>
</div>
</body>
</html>